/** TỪ ĐIỂN TIẾNG ANH — khoá là CÂU TIẾNG VIỆT nguyên văn. Xem `i18n.ts`.
 *
 * ⚠ Sửa một câu tiếng Việt trong mã mà quên sửa khoá ở đây thì câu ấy **rơi về tiếng
 * Việt** trong bản tiếng Anh, và không có gì báo. `tests/test_ngon_ngu.py` canh đúng
 * chuyện đó — nó quét mã nguồn, khoá nào không còn tìm thấy là hỏng.
 *
 * ⚠ Câu chưa có ở đây KHÔNG phải lỗi — nó hiện nguyên tiếng Việt. Dịch được từng phần
 * là chủ ý của cách khai khoá này (xem `i18n.ts`).
 */
import { EN2 } from './i18n_en2'
import { EN3 } from './i18n_en3'
import { EN4 } from './i18n_en4'

/** ⚠ MỘT bảng duy nhất, gom từ nhiều MẢNH. Tách file chỉ vì độ dài — chia thành hai
 *  bảng để hai chỗ tra thì "tra bảng nào trước" thành một câu hỏi không có đáp án đúng. */
const MANH: Record<string, string> = {
  // ------------------------------------------------------------------ Ribbon
  'Thêm khối': 'Add block',
  'Kiểm tra ĐK': 'Condition',
  'Vào lệnh': 'Open order',
  'Sửa lệnh': 'Modify order',
  'Sửa': 'Edit',
  'Nhân bản': 'Duplicate',
  'Xoá': 'Delete',
  'Luồng': 'Flow',
  'Đặt số ①': 'Set as ①',
  'Ghim số': 'Pin number',
  'Bỏ ghim': 'Unpin',
  'Vừa khung': 'Fit to screen',
  'Hoàn tác': 'Undo',
  'Làm lại': 'Redo',
  'Lưu': 'Save',
  'Mở': 'Open',
  'Tìm': 'Search',
  'Mã giao dịch': 'Symbol',
  'Tên chiến lược': 'Strategy name',
  'Tên chiến lược — cũng hiện trên thanh tiêu đề': 'Strategy name — also shown in the title bar',
  'Sơ đồ này đang có lỗi': 'This diagram has errors',
  'Sơ đồ ĐI SĂN — chạy một lượt mỗi nến. Chỉ nó được TẠO lệnh.':
    'The HUNTING diagram — runs once per candle. Only it may CREATE orders.',
  'Sơ đồ QUẢN LÝ — chạy một lượt cho MỖI lệnh đang sống. Chỉ nó được SỬA lệnh.':
    'The MANAGING diagram — runs once for EACH live order. Only it may MODIFY orders.',
  'Thêm cổng "Kiểm tra điều kiện" — nối nhiều cổng vào cùng một khối':
    'Add a "Check condition" gate — wire several gates into the same block',
  'Mở vị thế mới: Mua/Bán, loại lệnh, khối lượng, SL và TP ban đầu':
    'Open a new position: Buy/Sell, order type, size, initial SL and TP',
  'Tác động lên lệnh ĐÃ CÓ — bốn chế độ: dời SL · dời TP · SL về hoà vốn · kết thúc lệnh này':
    'Act on an EXISTING order — four modes: move SL · move TP · SL to break-even · close this order',
  'Mở hộp thoại sửa khối đang chọn (hoặc double-click vào khối)':
    'Open the editor for the selected block (or double-click the block)',
  'Nhân bản khối đang chọn (Ctrl+D)': 'Duplicate the selected block (Ctrl+D)',
  'Xoá khối đang chọn (Delete)': 'Delete the selected block (Delete)',
  'Biến khối đang chọn thành khối ① — khối chạy đầu tiên':
    'Make the selected block ① — the one that runs first',
  'Ghim số của khối đang chọn: mọi đường nối quay ngược về nó vẫn giữ':
    'Pin the selected block’s number: it keeps the number even when edges loop back to it',
  'Thu cả sơ đồ vào vừa màn hình': 'Fit the whole diagram on screen',
  'Mở Strategy Tester để chạy thử sơ đồ này (Ctrl+R)':
    'Open Strategy Tester to run this diagram (Ctrl+R)',
  'Mở cửa sổ Live — chạy trên kết nối thật (Ctrl+L)':
    'Open the Live window — run on a real connection (Ctrl+L)',
  'Mở cửa sổ RL — máy tự tìm chiến lược trong đúng kho đồ và luật':
    'Open the RL window — the machine searches for strategies inside the same toolkit and rules',

  // ---------------------------------------------------------------- TitleBar
  'Thu nhỏ': 'Minimize',
  'Phóng to': 'Maximize',
  'Khôi phục': 'Restore',
  'Đóng': 'Close',

  // ---------------------------------------------------------- SettingsDialog
  'Cài đặt': 'Settings',
  'Huỷ': 'Cancel',
  'Màu nhấn': 'Accent colour',
  'Mã mặc định': 'Default symbol',
  'Ngôn ngữ': 'Language',
  'Tiếng Việt': 'Vietnamese',
  'Tiếng Anh': 'English',
  'Chữ trên hộp khối do Python sinh — đổi ngôn ngữ ăn ngay, không phải mở lại app.':
    'Block card text is generated by Python — switching language takes effect immediately, no restart.',
  'Luật sàn': 'Broker rules',
  'Nguồn dữ liệu — nến M1': 'Data source — M1 candles',
  'Nhịp PHÁT LẠI — không phải tốc độ mô phỏng': 'REPLAY tick — not the simulation speed',
  'Vốn': 'Deposit',
  'Từ': 'From',
  'từ': 'from',
  'Đến': 'To',
  'Đang dùng': 'In use',
  'Kiểm tra kết nối MT5': 'Test MT5 connection',
  'đang nối…': 'connecting…',
  'Chưa hiệu chuẩn': 'Not calibrated',
  'chưa đo được': 'not measured yet',
  'chưa tải bộ nến nào': 'no candles downloaded yet',
  'lần nào, nên đang dùng': 'yet, so it is using',
  'số gõ tay': 'a hand-typed number',
  'số ĐO ĐƯỢC': 'the MEASURED number',
  'thiếu nến thì ▶ Chạy tự tải': 'missing candles are downloaded automatically on ▶ Run',
  '· trung vị đo được trên dữ liệu đã tải:': '· median measured on the downloaded data:',
  'không gọi được sang Python': 'could not reach Python',
  'không lưu được cài đặt': 'could not save settings',
  'Khoảng cách tối thiểu từ giá lệnh tới SL/TP. 0 = không chặn.':
    'Minimum distance from order price to SL/TP. 0 = no limit.',
  'Khối lượng làm tròn XUỐNG theo bước này': 'Volume is rounded DOWN to this step',
  'Sàn không nhận lệnh lớn hơn mức này': 'The broker rejects orders larger than this',
  'Sàn không nhận lệnh nhỏ hơn mức này': 'The broker rejects orders smaller than this',
  'Tính round-turn — trừ một lần khi lệnh đóng':
    'Charged round-turn — deducted once when the order closes',
  'Nến là giá Bid; Ask = Bid + spread. 0 = dùng số đo được từ kho nến.':
    'Candles are Bid; Ask = Bid + spread. 0 = use the number measured from the candle store.',
  'LUÔN theo chiều bất lợi — lệnh Stop ngoài đời khớp bằng hoặc xấu hơn giá kích hoạt. 0 = không mô hình hoá.':
    'ALWAYS adverse — a real Stop order fills at or worse than its trigger price. 0 = not modelled.',

  // ------------------------------------------------------------- cửa sổ RL
  'RL — tìm chiến lược': 'RL — strategy search',
  'Chạy': 'Run',
  'Dừng': 'Stop',
  'Dữ liệu': 'Data',
  'Lượt này': 'This run',
  'Lượt khác': 'Other runs',
  'Mổ xẻ': 'Dissect',
  'Vì sao rớt': 'Why rejected',
  'Đầu bảng': 'Top',
  'Đoạn khoá': 'Held-out',
  'Luật chơi · dữ liệu': 'Rules · data',
  'Kho đồ · thang số · trần · thưởng·phạt · dữ liệu · ngân sách · ghi chú':
    'Toolkit · ladders · caps · rewards·penalties · data · budget · notes',
  'Mở một lượt tìm trên luồng nền': 'Start a search run on a background thread',
  'Chấm nốt sơ đồ đang dở rồi ngừng': 'Finish the diagrams in flight, then stop',
  'Chạy lại với ĐÚNG cấu hình lượt này, không phải cấu hình đang đặt':
    'Re-run with EXACTLY this run’s configuration, not the one currently set',
  'chạy lại y hệt': 're-run identically',
  'Không chạy được.': 'Could not run.',
  'Không chạy lại được.': 'Could not re-run.',
  'Không mở được sơ đồ.': 'Could not open the diagram.',
  'Không mở được đoạn khoá.': 'Could not open the held-out run.',
  'Không nạp được cửa sổ RL.': 'Could not load the RL window.',
  'đang mở bàn điều khiển…': 'opening the dashboard…',
  '● đang chạy': '● running',
  'đang chạy': 'running',
  'đang chạy — mở khoá sau khi xong': 'running — the held-out check unlocks when it finishes',
  'đang đo…': 'measuring…',
  'đã chạy': 'elapsed',
  'đã dừng giữa chừng': 'stopped part-way',
  'còn': 'left',
  'chưa chạy lượt nào': 'no run yet',
  'chưa chạy lượt nào — bấm ▶ Chạy': 'no run yet — press ▶ Run',
  'chưa có lượt nào': 'no runs yet',
  'chưa có số nào': 'no numbers yet',
  'chưa có sơ đồ nào qua cửa': 'no diagram has passed the gates yet',
  'chưa sơ đồ nào qua cửa': 'no diagram has passed yet',
  'không sơ đồ nào qua cửa': 'no diagram passed the gates',
  'chưa sơ đồ nào qua cửa để soi': 'no diagram has passed yet to dissect',
  'chưa có sơ đồ nào qua cửa để mang sang đoạn khoá':
    'no diagram has passed yet to carry to the held-out range',
  'chọn một sơ đồ ở góc phải để soi': 'pick a diagram on the right to dissect',
  'bấm nút góc phải để chạy nhóm đầu bảng trên đoạn khoá':
    'press the button on the right to run the top group on the held-out range',
  'TIẾN ĐỘ': 'PROGRESS',
  'TÌM ĐƯỢC GÌ': 'WHAT WAS FOUND',
  'ĐẦU BẢNG': 'TOP DIAGRAMS',
  'CHẾT TRƯỚC CẢ CỬA': 'DEAD BEFORE THE GATES',
  'CỔNG NÀO GIẾT — theo toán hạng': 'WHICH GATE KILLS — by operand',
  'CHI PHÍ mỗi sơ đồ': 'COST per diagram',
  'Phân bố ĐIỂM': 'SCORE distribution',
  'Phân bố SỐ LỆNH': 'ORDER-COUNT distribution',
  'Mở sang cửa sổ vẽ': 'Open in the drawing window',
  'Kéo để nhường lại máy — ăn ngay, không đợi lượt sau':
    'Drag to give cores back — takes effect immediately, no need to wait',
  'mỗi sơ đồ': 'per diagram',
  'mỗi giờ': 'per hour',
  'gần đây': 'recently',
  'qua cửa': 'passed',
  'rớt cửa': 'rejected at a gate',
  'chết từ lúc vẽ': 'dead on arrival',
  'chết từ lúc vẽ — một cổng KHÔNG BAO GIỜ khớp':
    'dead on arrival — a gate that NEVER matches',
  'chạy mà không đẻ lệnh': 'ran but produced no order',
  'chạy mà không đẻ lệnh nào': 'ran but produced no order at all',
  'không lệnh nào': 'no orders',
  'nã lệnh': 'order spam',
  'quá nặng': 'too heavy',
  'trùng, bỏ qua': 'duplicate, skipped',
  'trùng sơ đồ đã chấm, bỏ qua': 'duplicate of a diagram already scored, skipped',
  'bộ chạy từ chối': 'engine refused',
  'lượt đi kẹt': 'walk got stuck',
  'còn tìm được gì nữa không — dừng được chưa':
    'is there anything left to find — can we stop yet',
  'cả đống, kể cả cái rớt cửa': 'the whole pile, rejected ones included',
  'cấu trúc của rác': 'the shape of the junk',
  "vì sao 'còn bao lâu' là một khoảng": 'why “time left” is a range',
  'dương n/m': 'positive n/m',
  '⚠ số TRAIN — và "dương n/m" mới là con số đáng đọc, không phải điểm':
    '⚠ TRAIN numbers — and “positive n/m” is the figure worth reading, not the score',
  'số TRAIN': 'TRAIN numbers',
  'điểm': 'score',
  'điểm train': 'train score',
  'điểm KHOÁ': 'HELD-OUT score',
  'đoạn khoá': 'held-out range',
  'đạt cửa?': 'passed?',
  'chênh': 'delta',
  'lãi': 'return',
  'lệnh': 'orders',
  'dương': 'positive',
  'hạt giống': 'seed',
  'nước đi': 'moves',
  'cái chung': 'what they share',
  'hình dạng theo cửa sổ': 'shape across windows',
  'bình thường': 'normal',
  'phẳng': 'flat',
  '— dừng được rồi': '— you can stop now',
  'vừa có thêm một cái qua cửa': 'another one just passed',
  'chưa sơ đồ nào qua cửa — đường sẽ hiện khi có cái đầu tiên':
    'no diagram has passed yet — the line appears with the first one',
  'rớt ở cửa': 'rejected at gate',
  'ngưỡng': 'threshold',
  'số sơ đồ': 'diagrams',
  'suýt qua': 'near miss',
  'suýt qua (<10%)': 'near miss (<10%)',
  'trượt xa bao nhiêu': 'how far off',
  'ví dụ': 'example',
  'nới cửa một chút thì có thêm bao nhiêu cái lọt':
    'how many more would pass if the gate were loosened a little',
  'thiếu 10–25%': 'off by 10–25%',
  'thiếu 25–50%': 'off by 25–50%',
  'thiếu 50–75%': 'off by 50–75%',
  'thiếu ≥75%': 'off by ≥75%',
  'kỳ có lệnh': 'periods with orders',
  'số lệnh tối thiểu': 'minimum orders',
  'sụt vốn': 'drawdown',
  'sụt vốn tối đa': 'max drawdown',
  'kỳ tệ nhất': 'worst period',
  'dao động tối đa': 'max volatility',
  'lãi tối thiểu': 'minimum return',
  'đều qua thời gian': 'steady over time',
  'không sống qua thời gian': 'does not survive over time',
  'điểm tối thiểu': 'minimum score',
  'tb tuần': 'weekly avg',
  'tb tháng': 'monthly avg',
  'dđ tuần': 'weekly vol',
  'dđ tháng': 'monthly vol',
  '. Mở': '. Open',
  '· đã mở': '· already open',
  'sổ ấy lên trước. Bấm vào nó trên thanh tác vụ.':
    'that window is already open. Click it on the taskbar.',
}

export const EN: Record<string, string> = { ...MANH, ...EN2, ...EN3, ...EN4 }
